import { Body } from "../types";

const COLORS = ["#FF4136", "#2ECC40", "#0074D9", "#FFDC00", "#B10DC9"];

export const PRESETS: Record<string, Body[]> = {
  figure8: [
    {
      id: 1,
      mass: 10,
      position: { x: 97.000436, y: -24.308753 },
      velocity: { x: 0.466203685, y: 0.43236573 },
      acceleration: { x: 0, y: 0 },
      radius: 5,
      color: COLORS[0],
      trail: [],
    },
    {
      id: 2,
      mass: 10,
      position: { x: -97.000436, y: 24.308753 },
      velocity: { x: 0.466203685, y: 0.43236573 },
      acceleration: { x: 0, y: 0 },
      radius: 5,
      color: COLORS[1],
      trail: [],
    },
    {
      id: 3,
      mass: 10,
      position: { x: 0, y: 0 },
      velocity: { x: -2 * 0.466203685, y: -2 * 0.43236573 },
      acceleration: { x: 0, y: 0 },
      radius: 5,
      color: COLORS[2],
      trail: [],
    },
  ],
  lagrange: [
    {
      id: 1,
      mass: 10,
      position: { x: 100, y: 0 },
      velocity: { x: 0, y: 2.5 },
      acceleration: { x: 0, y: 0 },
      radius: 6,
      color: COLORS[0],
      trail: [],
    },
    {
      id: 2,
      mass: 10,
      position: { x: -50, y: 86.6 },
      velocity: { x: -2.165, y: -1.25 },
      acceleration: { x: 0, y: 0 },
      radius: 6,
      color: COLORS[1],
      trail: [],
    },
    {
      id: 3,
      mass: 10,
      position: { x: -50, y: -86.6 },
      velocity: { x: 2.165, y: -1.25 },
      acceleration: { x: 0, y: 0 },
      radius: 6,
      color: COLORS[2],
      trail: [],
    },
  ],
  euler: [
    {
      id: 1,
      mass: 10,
      position: { x: 0, y: 0 },
      velocity: { x: 0, y: 0 },
      acceleration: { x: 0, y: 0 },
      radius: 8,
      color: COLORS[0],
      trail: [],
    },
    {
      id: 2,
      mass: 1,
      position: { x: 100, y: 0 },
      velocity: { x: 0, y: 3.5 },
      acceleration: { x: 0, y: 0 },
      radius: 4,
      color: COLORS[1],
      trail: [],
    },
    {
      id: 3,
      mass: 1,
      position: { x: -100, y: 0 },
      velocity: { x: 0, y: -3.5 },
      acceleration: { x: 0, y: 0 },
      radius: 4,
      color: COLORS[2],
      trail: [],
    },
  ],
  broucke: [
    {
      id: 1,
      mass: 10,
      position: { x: 0, y: 100 },
      velocity: { x: 1.5, y: 0 },
      acceleration: { x: 0, y: 0 },
      radius: 6,
      color: COLORS[3],
      trail: [],
    },
    {
      id: 2,
      mass: 10,
      position: { x: -86.6, y: -50 },
      velocity: { x: -0.75, y: 1.3 },
      acceleration: { x: 0, y: 0 },
      radius: 6,
      color: COLORS[4],
      trail: [],
    },
    {
      id: 3,
      mass: 10,
      position: { x: 86.6, y: -50 },
      velocity: { x: -0.75, y: -1.3 },
      acceleration: { x: 0, y: 0 },
      radius: 6,
      color: COLORS[0],
      trail: [],
    },
  ],
  random: [
    {
      id: 1,
      mass: 20,
      position: { x: 100, y: 0 },
      velocity: { x: 0, y: 1 },
      acceleration: { x: 0, y: 0 },
      radius: 8,
      color: COLORS[0],
      trail: [],
    },
    {
      id: 2,
      mass: 15,
      position: { x: -100, y: 0 },
      velocity: { x: 0, y: -1 },
      acceleration: { x: 0, y: 0 },
      radius: 6,
      color: COLORS[1],
      trail: [],
    },
    {
      id: 3,
      mass: 10,
      position: { x: 0, y: 150 },
      velocity: { x: 1, y: 0 },
      acceleration: { x: 0, y: 0 },
      radius: 5,
      color: COLORS[2],
      trail: [],
    },
  ],
};
